services:
  opentelemetry.login:
    image: ${DOCKER_REGISTRY-}opentelemetrylogin
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://userlogin.dashboard:18889
    networks:
     - otel

  userlogin.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
     - 18888:18888
    networks:
     - otel

networks:
  otel: